---
- name: include OS-specific variables
  tags: [logrotate, always]
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- name: include installation tasks
  tags: [logrotate, logrotate_install, install]
  ansible.builtin.import_tasks: installation.yml

- name: include configuration tasks
  tags: [logrotate, logrotate_config, config]
  ansible.builtin.import_tasks: configuration.yml
