---
- name: include OS-specific variables
  tags: [logrotate, always]
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family | lower }}.yml"

- import_tasks: installation.yml
  tags: [logrotate, logrotate_install, install]

- import_tasks: configuration.yml
  tags: [logrotate, logrotate_options, config]
